terraform project to deploy reddit-app instance
Otus-DevOps-2020-02/crisalid_infra pull request #5
Opened 2020-04-14 21:18 UTC by crisalid

# Выполнено ДЗ Terraform-1

 - [X] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Проект разворачивает из подготовленного с помощью Packer образа новый инстанс, устанавливает на него приложение reddit-app, и создает firewall-правило.

## Как запустить проект:
 - запустить команду terraform init, terraform plan, terraform apply в директории terraform

## Как проверить работоспособность:
 - перейти по ссылке http://35.205.194.187:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2020-04-14 21:45 UTC, mrgreyves requested changes
Здравствуйте!) Отправляю в доработку только затем что бы вы увидели оповещение. Измените версию терраформа и перезапустите тесты =)

2020-04-14 21:45 UTC, mrgreyves commented on terraform/main.tf
> +  required_version = "0.12.8"
попробуй установить версию 0.12

2020-04-14 21:58 UTC, crisalid commented on terraform/main.tf
> +  required_version = "0.12.8"
попробовал, не помогло
выполнил у себя команды, которые делает тревис - у меня они успешны

cd packer && packer validate -var-file=variables.json.example ubuntu16.json
Template validated successfully.

хотя странно, что в этом задании тревис проверяет и пакер тоже

2020-04-14 22:11 UTC, crisalid commented on terraform/main.tf
> +  required_version = "0.12.8"
поменял на примерную, ок
тесты прошли
спасибо

2020-04-15 10:13 UTC, mrgreyves approved these changes
Здравствуйте!) Все хорошо, апрув!)

2020-04-15 15:08 UTC, merged